# Generated by Django 5.2.7 on 2025-12-23 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Wallet',
            new_name='wallet',
        ),
    ]
