# Generated by Django 5.2.7 on 2025-12-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ('categories', '0001_initial'),
]

    operations = [
        migrations.CreateModel(
            name='DefaultCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=10)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'category_type')},
            },
        ),
    ]
