# Generated by Django 5.2.7 on 2025-12-22 02:05
from django.db import migrations

def create_default_categories(apps, schema_editor):
    DefaultCategory = apps.get_model('categories', 'DefaultCategory')
    
    defaults = [
        ("Salary", "INCOME"),
        ("Freelance", "INCOME"),
        ("Business Income", "INCOME"),
        ("Investment Income", "INCOME"),
        ("Gift", "INCOME"),
        ("Other Income", "INCOME"),
        
        ("Food & Dining", "EXPENSE"),
        ("Transport", "EXPENSE"),
        ("Rent/Mortgage", "EXPENSE"),
        ("Utilities", "EXPENSE"),
        ("Entertainment", "EXPENSE"),
        ("Shopping", "EXPENSE"),
        ("Healthcare", "EXPENSE"),
        ("Education", "EXPENSE"),
        ("Insurance", "EXPENSE"),
        ("Personal Care", "EXPENSE"),
        ("Other Expense", "EXPENSE"),
    ]
    
    for name, cat_type in defaults:
        DefaultCategory.objects.get_or_create(name=name, category_type=cat_type)

class Migration(migrations.Migration):
    dependencies = [
        ('categories', '0003_defaultcategory'),
    ]

    operations = [
        migrations.RunPython(create_default_categories),
    ]